# Generated by Django 3.0.8 on 2020-07-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('nombre_receptor', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['direccion'],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Base')),
            ],
            options={
                'ordering': ['chapa'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Base')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('num_ci', models.PositiveIntegerField()),
                ('profesion', models.CharField(max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Base')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Transporte')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Base')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Domicilio')),
                ('producto', models.ManyToManyField(to='Atajo.Producto')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atajo.Transporte')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
