# Generated by Django 3.0.8 on 2021-11-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Atajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('apodo', models.CharField(max_length=10)),
                ('num_ci', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('consejo_popular', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.PositiveIntegerField()),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
                ('pos_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['direccion'],
            },
        ),
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('f_siembra', models.DateField()),
                ('f_germinacion', models.DateField()),
                ('f_trasplante', models.DateField()),
                ('f_cosecha', models.DateField()),
            ],
            options={
                'ordering': ['f_cosecha'],
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('Lb', 'Libra'), ('Kg', 'Kilogramo'), ('g', 'Gramo'), ('U', 'Unidad'), ('Lt', 'Lata'), ('Gc', 'Guacál')], default='Lb', max_length=2)),
                ('estado', models.CharField(choices=[('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], default='B', max_length=1)),
                ('fecha_cosecha', models.DateField()),
                ('codigo', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('GRA', 'GRANO'), ('ELA', 'ELABORADO'), ('PLA', 'PLANTA')], default='GRA', max_length=3)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='Atajo.Cultivo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Obrero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('num_ci', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteSemillas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('d_plantas', models.PositiveIntegerField()),
                ('d_hileras', models.PositiveIntegerField()),
                ('d_profundidad', models.FloatField()),
                ('t_germinacion', models.PositiveIntegerField()),
                ('t_trasplante', models.PositiveIntegerField()),
                ('t_cosecha', models.PositiveIntegerField()),
                ('p_biocida', models.PositiveIntegerField()),
                ('p_fungicida', models.PositiveIntegerField()),
                ('p_fertilizante', models.PositiveIntegerField()),
                ('agricultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaqueteSemillas', to='Atajo.Agricultor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=30, null=True)),
                ('municipio', models.CharField(blank=True, max_length=30, null=True)),
                ('consejo_popular', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('pos_id', models.IntegerField()),
                ('agricultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parcela', to='Atajo.Agricultor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('itinerario', jsonfield.fields.JSONField()),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='base',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='base',
        ),
        migrations.RemoveField(
            model_name='ordenentrega',
            name='base',
        ),
        migrations.RemoveField(
            model_name='ordenentrega',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='ordenentrega',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='base',
        ),
        migrations.AddField(
            model_name='ordenentrega',
            name='ruta_asig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenentrega',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenentrega',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdenEntrega', to='Atajo.Transporte'),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='ruta',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ruta', to='Atajo.Transporte'),
        ),
        migrations.AddField(
            model_name='obrero',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Obrero', to='Atajo.Parcela'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='paquete_semillas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='Atajo.PaqueteSemillas'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='orden_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cultivo', to='Atajo.OrdenEntrega'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cultivo', to='Atajo.Parcela'),
        ),
        migrations.AddField(
            model_name='celda',
            name='paquete_semillas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Celda', to='Atajo.PaqueteSemillas'),
        ),
        migrations.AddField(
            model_name='celda',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Celda', to='Atajo.Parcela'),
        ),
        migrations.AddField(
            model_name='ordenentrega',
            name='agricultor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrdenEntrega', to='Atajo.Agricultor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenentrega',
            name='parcela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='Atajo.Parcela'),
            preserve_default=False,
        ),
    ]
