# Generated by Django 3.0.8 on 2021-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atajo', '0003_auto_20211109_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrero',
            name='movil',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
